version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk:23-slim-bullseye
  pre_build:
    commands:
      - echo Installing source dependencies...
      - mvn install -DskipTests
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Java application...
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/msagestaoprodutos-0.0.1-SNAPSHOT.jar
